### ISSUE TITLE
Rename the snapshot in dropbox

### ISSUE THREAD

**Issue by d0ugal** [d0ugal/hassio-dropbox-upload#15]
Having a list of slug names is a bit of a pain. Could we rename them to something a bit easier? Maybe include the creation date?

**Comment by adrianmihalko** [comment]
Human readable file names would be awesome.

`Automated Backup 2018-11-09 [ff8bc83c]`

Maybe we should use templates:

`"custom_filename": "My Backup %Y-%m-%d [slug]"`
