### ISSUE TITLE
Hassio API Access Failing

### ISSUE THREAD

**Issue by d0ugal** [d0ugal/hassio-dropbox-upload#22]
```
2018-10-05 09:13:24,549 - ERROR - Unhandled error
Traceback (most recent call last):
  File "upload.py", line 212, in main
    snapshots = list_snapshots()
  File "upload.py", line 62, in list_snapshots
    snapshots = hassio_get("snapshots")["snapshots"]
  File "upload.py", line 55, in hassio_get
    r.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://hassio/snapshots
```

I have started seeing this error constantly and my uploads are not working. Is anyone else seeing this? Or is it just my setup?

**Comment by d0ugal** [comment]
Looks like the dropbox sync addon is also having this issue: https://github.com/danielwelch/hassio-dropbox-sync/issues/11

**Comment by IoTmessenger** [comment]
I have the same errors in the log. Worked OK up till today (last upload was my backup from yesterday morning).

[EDIT}
Only change on my side, I did update from Hass.io version 0.79.1 to 0.79.3 yesterday.

After a restart of the add-on, the log shows:

```
2018-10-05 10:55:59,728 - INFO - Starting Snapshot backup
2018-10-05 10:55:59,741 - ERROR - Unhandled error
Traceback (most recent call last):
  File "upload.py", line 212, in main
    snapshots = list_snapshots()
  File "upload.py", line 62, in list_snapshots
    snapshots = hassio_get("snapshots")["snapshots"]
  File "upload.py", line 55, in hassio_get
    r.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://hassio/snapshots
```

**Comment by d0ugal** [comment]
@IoTmessenger did you recently upgrade homeassistant too? I guess it is related to the most recent version.

**Comment by IoTmessenger** [comment]
> @IoTmessenger did you recently upgrade homeassistant too? I guess it is related to the most recent version.

Yes, yesterday, see my edit above.

[EDIT]
In the hass.io log, I get this warning and error:

```
18-10-05 08:36:52 WARNING (MainThread) [hassio.api.security] /snapshots no role for 8aef3602_dropbox_upload
18-10-05 08:36:52 ERROR (MainThread) [hassio.api.security] Invalid token for access /snapshots
```

So definitely related to some change in new Hass.io version. 
Maybe adding support for the 'Long-Lived Access Token' option is a solution for the add-on?

**Comment by d0ugal** [comment]
Fixed here: https://github.com/d0ugal/hassio-dropbox-upload/commit/763e1af11a25343ab3b05dc1dcd565738be0a116

I had to uninstall the addon and reinstall it to force it to update. I'm not sure how often it updates otherwise with a git repo? (I really need to start publishing docker images)

**Comment by IoTmessenger** [comment]
Confirmed: working again for me as well!
