### ISSUE TITLE
Unable to install addon after installing on new SD card

### ISSUE THREAD

**Issue by captaindaveman** [d0ugal/hassio-dropbox-upload#49]
I am running 0.89.2 and had addon working perfectly, I recently upgraded my SD Card and reinstalled everything, I cannot now get the addon to install, the install button thinks for a min then goes red and I get the following error message:

19-03-20 14:33:34 ERROR (SyncWorker_7) [hassio.docker.interface] Can't install d0ugal/hassio-dropbox-upload-armv7:1.1.2 -> 404 Client Error: Not Found ("pull access denied for d0ugal/hassio-dropbox-upload-armv7, repository does not exist or may require 'docker login'").

Any ideas what I've not done, or done buts shouldn't have!

**Comment by klovatt** [comment]
I have just come across exactly the same issue.

Even restoring the addon from a snapshot does not work.

**Comment by d0ugal** [comment]
Interesting. It sounds like something has changed which has in turn is causing it to look for a different image name. I'm not really sure how to resolve this. So maybe we need to build armv7 also maybe?

You can see the image names here: https://hub.docker.com/u/d0ugal/

**Comment by mao-dzedun** [comment]
I have the same error on two different installations.

**Comment by captaindaveman** [comment]
I wonder if a footprint is left behind from a previous installation?

Kind Regards
Dave

________________________________

**Comment by freekeys** [comment]
I’m new to this add on and it’s not letting me install either :(

**Comment by tsvi** [comment]
Same here. Maybe it's because I moved from 64 bit to 32 bit version?
Or maybe due to HassOS upgrade to 2.11?

From https://github.com/home-assistant/hassos/releases

> HassOS Release 2 build 11 (Stable)

> @pvizeli pvizeli released this 4 days ago
> changed

>    OS: Enable systemd-coredump
>    OS: Add support for privileged supervisor
>    OS: Fix boot problem
>    OS: Disable coredump

**This version use now the new armv7 architecture for CLI/Supervisor.**

**Comment by freekeys** [comment]
Is anyone managing to install this at all? Even on fresh Hassio installations? Might be worth changing the issue name to “Cannot install on Hassio”

**Comment by d0ugal** [comment]
Works fine for me on an amd64 machine 😀 the error makes it look like it is a arm7 issue.

**Comment by tsvi** [comment]
@d0ugal See my comment above. HassOS 2.11 moved to the armv7 architecture.

**Comment by d0ugal** [comment]
Right, so it might be specific to the new "HassOS" and not hassio. Sorry, I had missed your comment and just read the one before mine. That seems likely but I am not sure how to handle that. I don't use HassOS.

This project needs an overhaul when it comes to building images anyway. We use [hassio-addons/build-env](https://github.com/hassio-addons/build-env) but that project has been archived. There must be a better way for us to do the bulds.

Fixing this would likely just require updating these two scripts. https://github.com/d0ugal/hassio-dropbox-upload/tree/master/scripts

If somebody can figure out how other projects are handling this I would be happy to try and update.

**Comment by tsvi** [comment]
@dougal, the hassio-addons repo now uses the following script which uses the Gitlab CI for creating docker images:

https://github.com/hassio-addons/organization/blob/master/gitlabci/addon.yml

Each addon has its own .gitlab-ci.yaml (see eg. https://github.com/hassio-addons/addon-ssh/blob/master/.gitlab-ci.yml)

If I have some spare time later in the day or tomorrow, I'll try to create a PR based on the script in the addon.yml for building and publishing.

In any case, you could use the existing infra to add armv7 in .travis.yml for the mean time so we can close this issue.

**Comment by dougal** [comment]
FAO @d0ugal.

**Comment by d0ugal** [comment]
Can somebody test this again now that #53 has been merged and a release will be out shortly (once this build finishes https://travis-ci.org/d0ugal/hassio-dropbox-upload/builds/512987969 )

**Comment by d0ugal** [comment]
Apologies, it seems I messed up the release (I hadn't done one for a while!). The release was fine, but i forgot to increase the version number, so hass.io didn't think there was an update.

Version 1.1.4 will be out once this build finishes. https://travis-ci.org/d0ugal/hassio-dropbox-upload/builds/513003059

**Comment by captaindaveman** [comment]
I tested this on HassOS 2.10, HA 0.90.2.
Fresh install, installed fine, tested and it works fine e.g. snapshot backed up to Dropbox and deleted required older snapshots from both Dropbox and HA.

Top job folks!

Sent from my iPhone

On 29 Mar 2019, at 12:53, Dougal Matthews <notifications@github.com<mailto:notifications@github.com>> wrote:


Apologies, it seems I messed up the release (I hadn't done one for a while!). The release was fine, but i forgot to increase the version number, so hass.io<http://hass.io> didn't think there was an update.

Version 1.1.4 will be out once this build finishes. https://travis-ci.org/d0ugal/hassio-dropbox-upload/builds/513003059<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftravis-ci.org%2Fd0ugal%2Fhassio-dropbox-upload%2Fbuilds%2F513003059&data=02%7C01%7C%7Ce469ca17a9df4ff316da08d6b4459c11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636894608391390628&sdata=08l66aHeCPKjX9S1%2FdI25IsdOXFmUDJXdcOczOu%2F3xw%3D&reserved=0>
