### ISSUE TITLE
Add a sensor for snapshots

### ISSUE THREAD

**Issue by d0ugal** [d0ugal/hassio-dropbox-upload#5]
How many are there?
Are they all backed up?
How big are they?

**Comment by d0ugal** [comment]
This might not belong in the addon.
Maybe I’ll need an accompanying custom component.
Or we can send details over MQTT

**Comment by IoTmessenger** [comment]
Maybe the watchdog also can provide this info and output the stats over MQTT. Easy to implement MQTT sensors for receiving the stats in Hass.

**Comment by d0ugal** [comment]
Closing in favour of #23
