### ISSUE TITLE
Dropbox files keep updating repeatedly

### ISSUE THREAD

**Issue by dspille** [d0ugal/hassio-dropbox-upload#59]
Since installing today's update, the add-in keeps wanting to update the dropbox files.  It's been updating the same files over and over all day long.  Any ideas?

`2020-08-17 15:19:52,571 - WARNING - The snapshot conflicts with a file name in dropbox, the contents are different. The dropbox file will be deleted and replaced. Local hash:

**Comment by d0ugal** [comment]
I have seen something like this too. I'm looking into a fix

**Comment by d0ugal** [comment]
Please update again. Seems to be working fine for me now.

**Comment by dspille** [comment]
Seems to be working now.  Thank you!

**Comment by dspille** [comment]
Confirmed that update 1.2.10 resolves the issue.
