### ISSUE TITLE
[doc] scope before token generation

### ISSUE THREAD

**Issue by gsemet** [d0ugal/hassio-dropbox-upload#60]
Hello,

Can you add a remark in your README in order to let user know they need to set the scope (especially `files.content.write/read`) BEFORE generating the token, because the permission changes are not reflected in already existing tokens.

**Comment by d0ugal** [comment]
Sure, a pull request would be welcome! I only just learned this now :smile:

**Comment by gsemet** [comment]
took me many many hours actually to find this !

**Comment by d0ugal** [comment]
Good job tracking it down
