### ISSUE TITLE
Logging shows only error data

### ISSUE THREAD

**Issue by IoTmessenger** [d0ugal/hassio-dropbox-upload#9]
There is no output in the Log view on the addon page in Hass.io while the addon is running. Except when there is an error to present.
Latest Hass.io v 0.77.3 running in Docker on an Intel NUC with Ubuntu server 18.04.1 LTS

As shown in a screenshot posted by @d0ugal , the script should be presenting information during the process.
This was also reported by @nigel914 in [ issue #7 ](https://github.com/d0ugal/hassio-dropbox-upload/issues/7)

Testing on another (older Hass.io v 0.75.3) instancein a VM, I got the same issue.

**Comment by d0ugal** [comment]
Thanks, I just reinstalled the addon and I lost the logging output. So that means a recent change I made must have introduced this error. I'll do some investigation.
